config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'dashboard#index'
  resources :user_feeds, only: [:index, :create, :destroy]

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  has_many :user_feeds
  has_many :users, through: :user_feeds
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_feeds
  has_many :feeds, through: :user_feeds
end

app/models/user_feed.rb
class UserFeed < ActiveRecord::Base
  belongs_to :feed
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  require 'pry' if Rails.env == 'development' || Rails.env == 'test'
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/user_feeds_controller.rb
class UserFeedsController < ApplicationController
  def index
    all_feeds = Feed.all
    @feeds = current_user.feeds
    @feeds_collection = all_feeds - @feeds
    @user_feed = current_user.user_feeds.new
  end

  def create
    begin
      current_user.user_feeds.create(permitted_data)
      flash[:success] = t('flash.successfully_added_rss_feed_to_the_list')
    rescue
      flash[:error] = t('flash.could_not_add_rss_feed_to_the_list')
    end

    redirect_to action: :index
  end

  def destroy
    begin
      user_feed = current_user.user_feeds.find_by_feed_id(params[:id])
      user_feed.delete

      flash[:success] = t('flash.successfully_deleted_rss_feed_from_the_list')
    rescue
      flash[:error] = t('flash.could_not_add_rss_feed_to_the_list')
    end

    redirect_to action: :index
  end

  private
  def permitted_data
    params[:user_feed].permit(
      :feed_id
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/user_feeds_helper.rb
module UserFeedsHelper
end

app/views/dashboard/index.html.erb
<h1><%= t('navbar.dashboard') %></h1>

app/views/layouts/_logged_in_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <ul class="nav navbar-nav navbar-left">
      <li class="<%= 'active' if active == 'dashboard' %>">
        <%= link_to root_path do %>
          <i class="fa fa-home"></i> <%= t('navbar.dashboard') %>
        <% end %>
      </li>

      <li class="<%= 'active' if active == 'user_feeds' %>">
        <%= link_to user_feeds_path do %>
          <i class="fa fa-rss"></i> <%= t('navbar.my_feeds') %>
        <% end %>
      </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <p class="navbar-text">
        <%= t('navbar.signed_in_as') %> <%= current_user.email %>
      </p>

      <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-power-off"></i> <%= t('navbar.logout') %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nwsfd</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

  <body>
    <div class="container">
      <% if user_signed_in? %>
        <%= render partial: 'layouts/logged_in_nav', locals: { active: params[:controller] } %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/user_feeds/_feed.html.erb
<tr>
  <td>
    <%= link_to user_feed_path(feed.id), method: :delete, class: 'btn btn-default' do %>
      <i class="fa fa-trash-o"></i>
    <% end %>
  </td>
  <td><%= feed.name %></td>
  <td><%= feed.rss_url %></td>
</tr>

app/views/user_feeds/index.html.erb
<h1><%= t('navbar.my_feeds') %></h1>

<%= form_for @user_feed, html: { class: 'form-inline' } do |f| %>
  <%= f.label :available_rss_feeds, t('forms.available_rss_feeds') %>
  <%= f.select :feed_id, options_from_collection_for_select(@feeds_collection, :id, :name), {}, class: 'form-control' %>
  <%= f.submit t('forms.add_rss_feed'), class: 'btn btn-primary' %>
<% end %>

<table class="table table-stripped">
  <thead>
    <tr>
      <th class="col-md-1"><%= t('lists.actions') %></th>
      <th class="col-md-2"><%= t('lists.name') %></th>
      <th class="col-md-9"><%= t('lists.rss_url') %></th>
    </tr>
  </thead>

  <tbody>
    <%= render partial: 'user_feeds/feed', collection: @feeds %>
  </tbody>
</table>